/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const GieEleInput: typeof import('@giegie/components')['GieEleInput']
  const GieEleRichText: typeof import('@giegie/components')['GieEleRichText']
  const GieInput: typeof import('@giegie/components')['GieInput']
}
